"""baseline — schema applied by installer/migrations/001_initial.sql.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-05-07
"""
from __future__ import annotations

# Alembic identifiers.
revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """No-op.

    The full schema (tenants, users, agents, voices, knowledge_bases,
    kb_documents, vicidial_servers, deployments, calls, call_events,
    nodes, audit_log, schema_migrations) is created by the bash migration
    runner in installer/lib/migrate.sh applying installer/migrations/
    001_initial.sql before alembic ever runs.

    This baseline simply stamps the schema version so Alembic considers
    the database "up to date" and any future autogenerated migrations
    diff against the existing state.
    """


def downgrade() -> None:
    """No-op — see upgrade docstring."""
