#!/usr/bin/env bash
# installer/lib/secrets.sh — generate and load /etc/aipanel/secrets.env.
#
# Idempotent: secrets.env is generated exactly once on first install. Re-runs
# leave it untouched. NEVER regenerate manually — doing so invalidates every
# Fernet-encrypted DB row (vici passwords, AMI passwords, etc).

set -euo pipefail

SECRETS_FILE="${SECRETS_FILE:-${AIPANEL_ETC}/secrets.env}"

# secrets_fernet_key — 32 random bytes, urlsafe-base64 with padding (44 chars).
# This is the exact format cryptography.fernet.Fernet expects.
secrets_fernet_key() {
    # openssl base64 uses + and / which Fernet rejects; translate to URL-safe.
    openssl rand 32 | base64 | tr '+/' '-_' | tr -d '\n'
    echo
}

# secrets_hex32 — 32 random bytes hex-encoded (64 chars). Fine for passwords.
secrets_hex32() {
    openssl rand -hex 32
}

# secrets_generate — create the file if missing. Owner: aipanel:aipanel 0600.
secrets_generate() {
    if [[ -f "${SECRETS_FILE}" ]]; then
        log_info "Secrets already exist at ${SECRETS_FILE} (preserved)."
        return 0
    fi
    log_info "Generating ${SECRETS_FILE} (one-time)"
    install -d -m 0750 -o root -g "${AIPANEL_GROUP}" "${AIPANEL_ETC}"

    # Build under a strict umask so the temp file never has loose perms.
    local tmp
    tmp="$(mktemp "${AIPANEL_ETC}/.secrets.env.XXXXXX")"
    chmod 0600 "${tmp}"
    cat > "${tmp}" <<EOF
# /etc/aipanel/secrets.env
# Generated by aipanel installer at $(date -Iseconds).
# DO NOT regenerate; regenerating invalidates all Fernet-encrypted DB rows.
# Format: KEY=VALUE, sourced by python-dotenv and the installer.

DB_PASSWORD=$(secrets_hex32)
REDIS_PASSWORD=$(secrets_hex32)
MINIO_ACCESS_KEY=aipanel
MINIO_SECRET_KEY=$(secrets_hex32)
JWT_SECRET=$(secrets_hex32)
ENCRYPTION_KEY=$(secrets_fernet_key)
EOF
    chown "${AIPANEL_USER}:${AIPANEL_GROUP}" "${tmp}"
    mv "${tmp}" "${SECRETS_FILE}"
    chmod 0600 "${SECRETS_FILE}"
}

# secrets_load — sources the file into the current shell so subsequent
# steps (postgres role creation, etc.) can read $DB_PASSWORD etc. The
# `set -a` causes every variable assignment to be auto-exported.
secrets_load() {
    [[ -f "${SECRETS_FILE}" ]] || die "Secrets not generated yet: ${SECRETS_FILE}"
    set -a
    # shellcheck disable=SC1090
    . "${SECRETS_FILE}"
    set +a
}

# secrets_ensure_field <KEY> <generator-fn>
#   Append KEY=<generator output> to secrets.env if KEY is missing. Used to
#   evolve the schema without rotating existing secrets — re-running install.sh
#   on an older box tops up new fields like SESSION_MGR_TOKEN without
#   regenerating DB_PASSWORD or ENCRYPTION_KEY.
secrets_ensure_field() {
    local key="${1:?usage: secrets_ensure_field KEY generator}"
    local generator="${2:?usage: secrets_ensure_field KEY generator}"
    [[ -f "${SECRETS_FILE}" ]] || die "Secrets not generated yet: ${SECRETS_FILE}"
    if grep -q "^${key}=" "${SECRETS_FILE}"; then
        log_debug "secret ${key} already present"
        return 0
    fi
    log_info "Adding new secret ${key} to ${SECRETS_FILE}"
    local val
    val="$(${generator})"
    # Preserve existing perms/ownership.
    printf '%s=%s\n' "${key}" "${val}" >> "${SECRETS_FILE}"
}
